# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: lochgeo's blog
description: >- # this means to ignore newlines until "baseurl:"
  The code behind the magic
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lochgeo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/lg-logos_transparent.png"

# Author
author:
  name: lochgeo
  avatar: "/images/lg-logos_transparent.png"

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-include-cache

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - day
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# Navigation
main:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Search"
    url: "/search/"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lochgeo/lochgeo.github.io"
    - label: "X"
      icon: "fab fa-fw fa-x"
      url: "https://x.com/lochgeo"

# Google Analytics
google_analytics_ga4: G-W2NYSGMPTH

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME