source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "minimal-mistakes-jekyll"
gem "jekyll-include-cache"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-paginate-v2"
gem "jekyll-archives"
gem "jekyll-remote-theme", "0.4.0"
gem "kramdown-parser-gfm"